version: '3'
services:
  consul:
    image: consul:latest
    restart: always
    entrypoint:
      - consul
    command:
      - agent
      - -client=0.0.0.0
      - -data-dir=/consul/data
      - -dev
    volumes:
      - consul-data:/consul/data:rw
    expose:
      - '8500'
    ports:
      - '8500:8500'
  nats:
    image: nats:latest
    restart: always
    command:
      - -a=0.0.0.0
      - -m=8222
      - -DV
    expose:
      - '4222'
    ports:
      - '4222:4222'
      - '8222:8222'
volumes:
  consul-data:
    driver: local